version: "3"
services:
  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prom_data:/prometheus
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  prom_node_exporter:
    image: prom/node-exporter
    container_name: prom_node_exporter
    ports:
    - 9100:9100
    command:
    - "--path.rootfs=/host"
    volumes:
    - "/:/host:ro,rslave"
    pid: host
    restart: always
  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
volumes:
  grafana_data:
  prom_data: