scrape_configs:
  - job_name: 'node'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['prom_node_exporter:9100']
        labels:
          group: 'node'